# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# https://docs.spring.io/spring-boot/docs/2.0.4.RELEASE/reference/html/common-application-properties.html
# ===================================================================

spring:
    thymeleaf:
        cache: false
    infinity-rpc:
        registry:
            address: 127.0.0.1:2181
# ===================================================================
# Application specific properties
# ===================================================================
# ===================================================================
# Application specific properties
# ===================================================================