# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# https://docs.spring.io/spring-boot/docs/2.3.0.RELEASE/reference/html/common-application-properties.html
# ===================================================================
info: # These configurations can be exported to Environment, accessing URL /management/info can get these properties
    artifact:
        id: @project.artifactId@
        version: @project.version@
    project:
        package: org.infinity.luix.portal
spring:
    application:
        name: ${info.artifact.id}
    profiles:
        # The commented value for `active` can be replaced with valid spring profiles to load.
        # Otherwise, it will be filled in by maven when building the WAR file
        # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
        active: @spring.profiles.active@
    messages:
        basename: i18n/messages
    thymeleaf: #ThymeleafAutoConfiguration
        mode: HTML
    banner:
        location: classpath:config/banner-company.txt
server:
    # It can be overridden by `--server.port` value passed in the commandline or `-Dserver.port` set in `JAVA_OPTS`
    port: @app.server.port@
    servlet:
        session:
            cookie:
                name: ${spring.application.name}
logging:
    config: classpath:config/logback-spring.xml
    file:
        path: ${user.home}${file.separator}Log${file.separator}${spring.application.name}${file.separator}${spring.application.name}
    level:
        root: DEBUG
        ${info.project.package}: DEBUG
# ===================================================================
# Application specific properties
# ===================================================================
application:
    http:
        cache: # Used by the CachingHttpHeadersFilter
            expired-after: 31
