# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# Full reference is available at:
# https://docs.spring.io/spring-boot/docs/2.3.0.RELEASE/reference/html/appendix-application-properties.html
# ===================================================================
app:
    id: @project.artifactId@
    name: @project.name@
    version: @project.version@
    package: org.infinity.luix.portal
spring:
    application:
        name: ${app.id}
    profiles:
        # The commented value for `active` can be replaced with valid spring profiles to load.
        # Otherwise, it will be filled in by maven when building the WAR file
        # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
        active: @spring.profiles.active@
    messages:
        basename: i18n/messages
    thymeleaf: #ThymeleafAutoConfiguration
        mode: HTML
    banner:
        location: classpath:config/banner-company.txt
server:
    # It can be overridden by `--server.port` value passed in the commandline or `-Dserver.port` set in `JAVA_OPTS`
    port: @app.server.port@
    servlet:
        session:
            cookie:
                name: ${spring.application.name}
logging:
    config: classpath:config/logback-spring.xml
    level:
        root: INFO
# ===================================================================
# Application specific properties
# ===================================================================
application:
    swagger:
        enabled: true
        api:
            title: @project.name@ API
            description: @project.name@接口文档
        version: ${app.version}
        contact-name: 刘尧
        contact-email: liuyao@xforceplus.com
    http:
        cache: # Used by the CachingHttpHeadersFilter
            expired-after: 31
