# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# Full reference is available at:
# https://docs.spring.io/spring-boot/docs/2.5.5/reference/html/application-properties.html#application-properties
# ===================================================================
app:
    id: luix-portal
    name: luix-portal
    version: 1.0.0
    package: org.infinity.luix.portal
spring:
    application:
        name: ${app.id}
    profiles:
        #It can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
        active: dev
    messages:
        basename: i18n/messages
    thymeleaf: #ThymeleafAutoConfiguration
        mode: HTML
    banner:
        location: classpath:config/banner-company.txt
server:
    # It can be overridden by `--server.port` value passed in the commandline or `-Dserver.port` set in `JAVA_OPTS`
    port: 6040
    servlet:
        session:
            cookie:
                name: ${spring.application.name}
logging:
    config: classpath:config/logback-spring.xml
    level:
        root: INFO
# ===================================================================
# Application specific properties
# ===================================================================
application:
    swagger:
        enabled: true
        api:
            title: @project.name@ API
            description: @project.name@接口文档
        version: ${app.version}
        contact-name: Louis
        contact-email: louis@luixtech.com
    http:
        cache: # Used by the CachingHttpHeadersFilter
            expired-after: 31
