spring:
    data:
        mongodb:
            uri: mongodb://admin:79Gfs87J3YhS23YH@192.168.1.101:34003/${spring.application.name}
luix-rpc:
    registry:
        host: localhost
        port: 8500
# ===================================================================
# Application specific properties
# ===================================================================
