# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# Full reference is available at:
# https://docs.spring.io/spring-boot/docs/3.2.0/reference/html/application-properties.html#application-properties
# ===================================================================
app:
    id: luix-rpc-web-center
    name: luix-rpc-web-center
    version: 1.0.0
    package: com.luixtech.rpc.webcenter
    companyName: Infinity Organization
management: # Management http server configuration, used by ManagementServerProperties
    health:
        mongo:
            enabled: true
    endpoints:
        web:
            base-path: /management
            exposure:
                include:
                    - configprops
                    - env
                    - health
                    - beans
                    - mappings
                    - httptrace
                    - shutdown
                    - auditevents
                    - scheduledtasks
                    - loggers
                    - prometheus
                    - threaddump
    endpoint:
        health: # used by HealthEndpointProperties, Note: it will show health details if it has the access token by Ajax
            enabled: true
            show-details: WHEN_AUTHORIZED
        httptrace:
            enabled: true
        shutdown:
            enabled: true # explicitly enable
spring:
    application:
        name: ${app.id}
    profiles:
        # It can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
        active: test
    messages:
        basename: i18n/messages,i18n/luix-messages
        fallback-to-system-locale: false
    task:
        execution:
            thread-name-prefix: global-async-task-
            pool:
                core-size: 5
                max-size: 32
                queue-capacity: 1000
        scheduling:
            thread-name-prefix: global-scheduling-
            pool:
                size: 10
    thymeleaf: #ThymeleafAutoConfiguration
        mode: HTML
    servlet:
        multipart: # Management http multipart configuration, used by MultipartProperties
            enabled: true
            max-file-size: 30MB
            max-request-size: 30MB
    mail: # specific mail property, used by MailProperties
        host: smtp.exmail.qq.com
        username: test@luixtech.cn
        password: LoU-UHR-9dH-8G9-F3G
    banner:
        location: classpath:config/banner-company.txt
    mongodb:
        embedded:
            version: 4.0.0
    data:
        mongodb:
            auto-index-creation: false
        web:
            pageable:
                one-indexed-parameters: false # whether to expose and assume 1-based page number indexes
                max-page-size: 2000
server:
    # It can be overridden by `--server.port` value passed in the commandline or `-Dserver.port` set in `JAVA_OPTS`
    port: 6030
    servlet:
        session:
            cookie:
                http-only: true
logging:
    config: classpath:config/logback-spring.xml
    level:
        root: INFO
# ===================================================================
# Luix RPC specific properties
# ===================================================================
luix-rpc:
    application:
        id: ${spring.application.name}
        description: RPC Web Center
        team: Infinity Team
        emailSuffixes: '@luixtech.cn'
        ownerEmail: louis@luixtech.cn
        env: ${spring.profiles.active}
    registries:
        0:
            name: consul
            connectTimeout: 1000
            sessionTimeout: 60000
    protocol:
        port: 1${server.port}
        serializer: hessian2
springdoc: # https://springdoc.org/#migrating-from-springfox
    api-docs:
        enabled: true
    show-actuator: true
    swagger-ui:
        tags-sorter: alpha
# ===================================================================
# Luix framework specific properties
# ===================================================================
luix:
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        logs: # print metrics info to the logs
            enabled: false
            report-frequency: 60 # in seconds
        graphite: # output metrics info to graphite server
            enabled: false
            host: localhost
            port: 2003
            prefix: ${spring.application.name}
    http:
        cache: # Used by the CachingHttpHeadersFilter
            expired-after: 31
    api-docs:
        api-include-pattern: /api/**
        open-api-include-pattern: /open-api/**
        management-include-pattern: /management/**
        api-title: LUI️✘ RPC Web Center API
        open-api-title: LUI️✘ RPC Web Center Open API
        management-title: LUI️✘ RPC Web Center Management
        version: ${app.version}
        terms-of-service-url:
        contact-name: Louis
        contact-url:
        contact-email: louis@luixtech.cn
        license: Unlicensed
        license-url:
    aop-logging:
        enabled: true
    elapsed-time-logging:
        enabled: true
        slow-execution-threshold: 300 # unit: ms
    ribbon:
        # comma separated list of profiles to show a ribbon on the GUI
        display-on-active-profiles: dev,test,demo
# ===================================================================
# Application specific properties
# ===================================================================
application:
    cors:
        allowed-methods: "*"
        allowed-headers: "*"
        exposed-headers: "Authorization,Link,X-Total-Count,X-${spring.application.name}-alert,X-${spring.application.name}-error,X-${spring.application.name}-params"
        allow-credentials: true
        max-age: 1800
    user-event-audit:
        enabled: true
    account:
        default-password: ${spring.application.name}
    security:
        content-security-policy: "frame-src 'self' data:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://storage.googleapis.com;"
        authentication:
            jwt:
                # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
                base64-secret: Epc4yo1VAtS10s7LzRis2NyTynSWAlggB9/iAdKHhkwI8JvgqV+gW3p+HFOVKiKuVYj37YgLaVKo0T+Fxlwynw==
                # Token is valid 24 hours
                token-validity-in-seconds: 86400
                token-validity-in-seconds-for-remember-me: 2592000