spring:
    data:
        mongodb:
            uri: mongodb://localhost:27017/${spring.application.name}
luix-rpc:
    registries:
        0:
            host: 10.10.10.60
            port: 8500
# ===================================================================
# Application specific properties
# ===================================================================