# ===================================================================
# Spring Boot configuration for the "demo" profile.
#
# This configuration overrides the application.yml file.
# Full reference is available at:
# https://docs.spring.io/spring-boot/docs/2.7.1/reference/html/application-properties.html#application-properties
# ===================================================================
luix:
    registries:
        0:
            host: 10.10.10.60
            port: 8500
# ===================================================================
# Application specific properties
# ===================================================================