# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
# Full reference is available at:
# https://docs.spring.io/spring-boot/docs/2.3.0.RELEASE/reference/html/appendix-application-properties.html
# ===================================================================
mongock:
    enabled: true
infinity:
    registry:
        host: localhost
        port: 2181
    protocol:
        port: @app.rpc.port@
# ===================================================================
# Application specific properties
# ===================================================================
