# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
# Full reference is available at:
# https://docs.spring.io/spring-boot/docs/2.3.0.RELEASE/reference/html/appendix-application-properties.html
# ===================================================================
luix:
    registry:
        host: 172.17.0.2
        port: 2181
#        providerAddresses: 127.0.0.1:16010
    protocol:
        port: @app.rpc.port@
# ===================================================================
# Application specific properties
# ===================================================================
