spring:
    data:
        mongodb:
            uri: mongodb://localhost:27017/${spring.application.name}
luix-rpc:
    registry:
        host: localhost
        port: 8500
# ===================================================================
# Application specific properties
# ===================================================================
