# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# Full reference is available at:
# https://docs.spring.io/spring-boot/docs/3.2.0/reference/html/application-properties.html#application-properties
# ===================================================================
management: # Management http server configuration, used by ManagementServerProperties
    endpoints:
        web:
            base-path: /management
            exposure:
                include:
                    - configprops
                    - env
                    - health
                    - beans
                    - mappings
                    - httptrace
                    - shutdown
                    - auditevents
                    - scheduledtasks
                    - loggers
                    - prometheus
                    - threaddump
    endpoint:
        health: # used by HealthEndpointProperties, Note: it will show health details if it has the access token by Ajax
            enabled: true
            show-details: WHEN_AUTHORIZED
        httptrace:
            enabled: true
        shutdown:
            enabled: false # explicitly enable
spring:
    application:
        name: luix-rpc-portal
    profiles:
        #It can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
        active: test
    messages:
        basename: i18n/messages,i18n/luix-messages
    thymeleaf: #ThymeleafAutoConfiguration
        mode: HTML
    banner:
        location: classpath:config/banner-company.txt
server:
    # It can be overridden by `--server.port` value passed in the commandline or `-Dserver.port` set in `JAVA_OPTS`
    port: 6040
    servlet:
        session:
            cookie:
                name: ${spring.application.name}
logging:
    level:
        root: INFO
        org.springframework.boot.devtools.autoconfigure: INFO
        org.apache: WARN
        org.mongodb.driver: WARN
        sun.rmi: WARN
        jdk.event.security: WARN
# ===================================================================
# Application specific properties
# ===================================================================
luix:
    swagger:
        enabled: true
        api:
            title: Luix Portal API
            description: Luix Portal接口文档
        version: 1.0.0
        contact-name: Louis
        contact-email: louis@luixtech.cn
    http:
        cache: # Used by the CachingHttpHeadersFilter
            expired-after: 31
