# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: luix
services:
  rpc-server-demo:
    image: luix-rpc-server-demo
    container_name: luix-rpc-server-demo
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=test
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/luix-rpc-server-demo
      - LUIX_RPC_REGISTRY_HOST=consul
    ports:
      - 127.0.0.1:4001:4001
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4001/management/health"]
      interval: 5s
      timeout: 5s
      retries: 40
  rpc-client-demo:
    image: luix-rpc-client-demo
    container_name: luix-rpc-client-demo
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=test
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - LUIX_RPC_REGISTRY_HOST=consul
    ports:
      - 127.0.0.1:4002:4002
    depends_on:
      rpc-server-demo:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4002/management/health"]
      interval: 5s
      timeout: 5s
      retries: 40
  consul:
    extends:
      file: ./consul.yml
      service: consul
  mongodb:
    extends:
      file: ./mongodb.yml
      service: mongodb