# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  luix-demo-server-docker:
    image: pm6422/luix-demo-server:1.0.0
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=dev
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
#      - SPRING_DATA_MONGODB_URI=mongodb://localhost:27017
#      - SPRING_DATA_MONGODB_DATABASE=luix-demo-server
      - SLEEP_TIME=30 # gives time for other services to boot before the application
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:6010:6010
  luix-demo-client-docker:
    image: pm6422/luix-demo-client:1.0.0
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=dev
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SLEEP_TIME=30 # gives time for other services to boot before the application
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:6020:6020
