# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  consul:
    container_name: consul
    image: consul:1.9
    networks:
      - consul
    ports:
      - 8500:8500
    command: ["consul","agent","-server","-bootstrap","-data-dir","/consul","-ui","-bind","127.0.0.1","-client","0.0.0.0"]
networks:
  consul:
    driver: bridge
