# ===================================================================
# Spring Boot configuration for the "test" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# https://docs.spring.io/spring-boot/docs/2.0.4.RELEASE/reference/html/common-application-properties.html
# ===================================================================
infinity:
    registry:
        protocol: zookeeper
        address: localhost:2181
# ===================================================================
# Application specific properties
# ===================================================================
