# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
# Full reference is available at:
# https://docs.spring.io/spring-boot/docs/2.5.5/reference/html/application-properties.html#application-properties
# ===================================================================
luix:
    registry:
        host: 10.10.10.60
        port: 8500
#        providerAddresses: 127.0.0.1:16010
# ===================================================================
# Application specific properties
# ===================================================================
application:
    url:
        appServiceProviderUrl: 10.10.10.60:16010