# ===================================================================
# Spring Boot configuration for the "demo" profile.
#
# This configuration overrides the application.yml file.
# Full reference is available at:
# https://docs.spring.io/spring-boot/docs/2.3.0.RELEASE/reference/html/appendix-application-properties.html
# ===================================================================
mongock:
    enabled: true
luix:
    registries:
        0:
            host: 172.17.0.2
            port: 2181
    protocol:
        port: @app.rpc.port@
# ===================================================================
# Application specific properties
# ===================================================================