# ===================================================================
# Spring Boot configuration for the "test" profile.
#
# This configuration overrides the application.yml file.
# Full reference is available at:
# https://docs.spring.io/spring-boot/docs/2.3.0.RELEASE/reference/html/appendix-application-properties.html
# ===================================================================
spring:
    data:
        mongodb:
            uri: mongodb://admin:79Gfs87J3YhS23YH@192.168.1.101:36030/${spring.application.name}
infinity:
    registry:
        host: localhost
        port: 2181
    protocol:
        port: @app.rpc.port@
# ===================================================================
# Application specific properties
# ===================================================================
